#!/usr/bin/node

const request = require('request');

const movieId = process.argv[2];
const url = `https://swapi-api.alx-tools.com/api/films/${movieId}/`;

request.get(url, function (error, response, body) {
  if (error) {
    console.error(error);
    return;
  }

  const film = JSON.parse(body);
  const characters = film.characters;
  let completedRequests = 0;

  characters.forEach((characterUrl) => {
    request.get(characterUrl, function (error, response, body) {
      if (error) {
        console.error(error);
        return;
      }

      const character = JSON.parse(body);
      console.log(character.name);

      completedRequests++;
      if (completedRequests === characters.length) {
        // All requests completed
        console.log('All characters printed.');
      }
    });
  });
});
